modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU LESSER GENERAL PUBLIC LICENSE"
issueTrackerURL="https://github.com/AlexModGuy/AlexsCavesBetaTest/issues" #optional
[[mods]] #mandatory
modId="alexscaves" #mandatory
version="1.0.9" #mandatory
displayName="Alex's Caves" #mandatory
displayURL="" #optional
authors="Alexthe668, Noonyeyz" #optional
credits="LudoCrypt, _Ninni, PrismaticPinky, RenRen, Gatetoh, arby698, PlummetStudios, HolidayRaptor" #optional
description='''Explore new rare cave biomes hidden under the surface of the Overworld...'''
logoFile="mod_logo.png" #optional
[[dependencies.alexscaves]] #optional
# the modid of the dependency
modId="citadel" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory=true #mandatory
# The version range of the dependency
versionRange="[2.1,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="AFTER"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"
[[dependencies.alexscaves]]
modId="forge"
mandatory=true
versionRange="[43.3.0,)"
ordering="NONE"
side="BOTH"